version: 2

jobs:
  build:
    docker:
    - image: holochain/holochain-rust:circle.01.warm.nix
    steps:
    - run:
        name: Starting test
        command: nix-shell
    - run:
        name: ls -la
        command: ls -la
