version: 2.1

jobs:
  build:
    docker:
    - image: holochain/holochain-rust:circle.01.warm.nix
    steps:
    - checkout
    - run:
        name: Starting test
        command: nix-shell --run hc-test
