version: 2
jobs:
  build:
    docker:
      - image: holochain/holochain-rust:latest

    steps:

      - run:
          name: clone hc rust
          command: git clone https://github.com/holochain/holochain-rust
      - run:
          name: install cli     
          command: cd holochain-rust && nix-shell --run hc-cli-install

      - checkout

      - run:
          name: build dna
          command: cd dna-src && hc package
