version: 2
jobs:
  build:
    docker:
      - image: holochain/holochain-rust:latest

    steps:
      - run:
          name: rustup
          command: rustup toolchain install nightly-2019-01-24 && rustup default nightly-2019-01-24 && rustup target add wasm32-unknown-unknown --toolchain nightly-2019-01-24

      - run:
          name: clone hc rust
          command: git clone https://github.com/holochain/holochain-rust
      - run:
          name: install cli     
          command: cd holochain-rust && nix-shell --run hc-cli-install

      - checkout:
          path: ~/Holo-Hosting-App

      - run:
          name: build dna
          command: cd ~/Holo-Hosting-App/dna-src && /root/.cargo/bin/hc package
