version: 2
jobs:
  build:
    docker:
      - image: holochain/holochain-rustbuild dna

    steps:
      - checkout

      - run:
          name: Greeting
          command: cd dna-src  && hc package

      - run:
          name: Print the Current Time
          command: date
