version: 2
jobs:
  build:
    docker:
            - image: samrose/holo-hc:cli-v0.0.12-alpha1

    steps:


      - checkout:
          path: ~/Holo-Hosting-App

      - run:
          name: build dna
          command: cd ~/Holo-Hosting-App/dna-src && /hc/cli-v0.0.12-alpha1-x86_64-unknown-linux-gnu/hc package
