version: 2

jobs:
  build:
    docker:
    - image: holochain/holonix:latest
    - image: circleci/node:10.15.1
    steps:
    - run:
        command: npm install
    - run:
        name: Starting test
        command: npm run ci-test
