version: 2
jobs:
  build:
    docker:
      - image: holochain/holochain-rust:latest

    steps:
      - checkout

      - run:
          name: build hc cli
          command: nix-shell --run hc-cli-install

      - run:
          name: build dna
          command: cd dna-src && hc package
