version: 2

jobs:
  build:
    docker:
    - image: holochain/holonix:latest
    steps:
    - run:
        name: Starting test
        command: nix-shell
    - run:
        name: ls -la
        command: ls -la
