version: 2
jobs:
  build:
    docker:
      - image: samrose/holo-hc:cli-v0.0.12-alpha1
    steps:


      - checkout:
          path: ~/Holo-Hosting-App

      - run:
          name: build dna
          command: cd ~/Holo-Hosting-App/dna-src && /home/circleci/cli-v0.0.12-alpha1-x86_64-unknown-linux-gnu/hc package
      
      - run:
          name: "publish release"
          command: |
            ghr -t $GITHUB_TOKEN -u samrose -r Holo-Hosting-App test1 /home/circleci/Holo-Hosting-App/dna-src/dist/      

workflows:
  version: 2
  workflow:
    jobs:
    - build
